name: Start SSH via Ngrok

on:
  push:
    branches:
      - test_ngork
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1

      - name: Try Build
        run: ./not-exist-file.sh it bloke build

      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://raw.githubusercontent.com/sdzbzyh/openwrt/refs/heads/main/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}

      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure
